### ISSUE TITLE
Call to undefined method PHPObjectSymbolResolver\Parser::parserFor()

### ISSUE THREAD

**Issue by cayolblake** [ircmaxell/php-object-symbolresolver#4]
Hi @bwoebi @ircmaxell 

Trying to run the demo.php example, I am getting the following error.

`PHP Fatal error:  Uncaught Error: Call to undefined method PHPObjectSymbolResolver\Parser::parserFor()`

Trying to search the library source code couldn't find `parserFor()` method.

Any idea?

**Comment by bwoebi** [comment]
Fixed, it's been renamed to parseFor(), but the file wasn't updated.
